version: '2'

services:
  db:
    image: mariadb
    container_name: "${COMPOSE_PROJECT_NAME}_db"
    command: mysqld --innodb-buffer-pool-size=20M --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - "MYSQL_DATABASE=db_test"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=user_passwd"
      - "MYSQL_ROOT_PASSWORD=root_passwd"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d
    networks:
      - code-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}_admin"
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - code-network
  app:
    build: config/php
    container_name: "${COMPOSE_PROJECT_NAME}_app"
    links:
      - db
    depends_on:
      - db
    restart: always
    expose:
      - "10000"
    volumes:
      - ./src/:/var/www
      - ./logs/xdebug/:/tmp/xdebug_log
    environment:
      XDEBUG_CONFIG: remote_host=192.168.32.1
    networks:
      - code-network
  nginx:
    image: nginx:latest
    container_name: "${COMPOSE_PROJECT_NAME}_ngnix"
    restart: always
    ports:
      - "80:80"
      - "4443:443"
    links:
      - app
    volumes:
      - ./src/:/var/www
      - ./logs/:/var/logs
      - ./config/nginx/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - code-network
networks:
  code-network:
    driver: bridge